# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DunesDetector
                                 A QGIS plugin
 This plugin creates temporal stacks of classified images to allow dunes detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-19
        copyright            : (C) 2019 by Maffioli Sara Vaghi Federica
        email                : saramaffioli@outlook.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DunesDetector class from file DunesDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dunes_detector import DunesDetector
    return DunesDetector(iface)
